title: Last Buck
author: taurenbuffet
email: addlater@
description: > # this means to ignore newlines until "baseurl:"
  A blog to discuss working in tech and having little technical 
  background.
# social links
twitter_username: your-twitter-handle
github_username:  taurenbuffet

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
